language: cpp
jobs:
  include:
    # Ubuntu 16.04
    - os: linux
      dist: xenial
    # Ubuntu 18.04
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10.1 # for CLANG 3.1
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap ilpincy/argos3      ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bash-completion ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt              ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      wget https://drive.google.com/open?id=1OVKPMZFa0GzSU1RwioaEReUCUl-vngkR
      sudo dpkg -i argos3_simulator-3.0.0-x86_64-beta56.deb
    fi
before_script:
  - ${CXX} --version
  - ${CXX} -v
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt              ; fi

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir -p build
  - cd build
  - cmake ../src 
  - make
