language: cpp
jobs:
  include:
    # Ubuntu 16.04
    - os: linux
      dist: xenial
    # Ubuntu 18.04
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10.1 # for CLANG 3.1
before_install:
  - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OVKPMZFa0GzSU1RwioaEReUCUl-vngkR' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OVKPMZFa0GzSU1RwioaEReUCUl-vngkR" -O argos3_simulator-3.0.0-x86_64-beta56.deb
  - rm -rf /tmp/cookies.txt
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap ilpincy/argos3      ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bash-completion ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink python@2         ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install argos3          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo dpkg -i "argos3_simulator-3.0.0-x86_64-beta56.deb"
    fi
before_script:
  - ${CXX} --version
  - ${CXX} -v
  
script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir -p build
  - cd build
  - cmake ../src 
  - make
